name: Prepare build environment

description: Prepares build environment for python and prompt flow related workflow execution.

inputs:
  versionSpec:
    description: "The Python version to use in the environment."
    default: "3.11"


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: ${{ inputs.versionSpec }}

    - name: Load all prompt flow and related dependencies
      shell: bash
      run: |
        set -e # fail on error
        python -m pip install --upgrade pip
        python -m pip install .

